// <auto-generated />
namespace dataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class INIT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(INIT));
        
        string IMigrationMetadata.Id
        {
            get { return "202101310747214_INIT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
